"""Initial migration.

Revision ID: c0df4cd8ad9a
Revises: 
Create Date: 2022-05-29 21:18:34.502701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0df4cd8ad9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('picture', 'repo_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('picture', 'pic_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('picture', 'img_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('picture_repo_id_fkey', 'picture', type_='foreignkey')
    op.create_foreign_key(None, 'picture', 'repository', ['repo_id'], ['repo_id'], ondelete='cascade')
    op.drop_constraint('picture_tag_picture_id_fkey', 'picture_tag', type_='foreignkey')
    op.create_foreign_key(None, 'picture_tag', 'picture', ['picture_id'], ['picture_id'], ondelete='cascade')
    op.alter_column('repository', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('repository', 'repo_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('repository_username_fkey', 'repository', type_='foreignkey')
    op.create_foreign_key(None, 'repository', 'user_account', ['username'], ['username'], ondelete='cascade')
    op.drop_column('tag', 'picture_id')
    op.alter_column('user_account', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_account', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_account', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_account', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('tag', sa.Column('picture_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'repository', type_='foreignkey')
    op.create_foreign_key('repository_username_fkey', 'repository', 'user_account', ['username'], ['username'])
    op.alter_column('repository', 'repo_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('repository', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'picture_tag', type_='foreignkey')
    op.create_foreign_key('picture_tag_picture_id_fkey', 'picture_tag', 'picture', ['picture_id'], ['picture_id'])
    op.drop_constraint(None, 'picture', type_='foreignkey')
    op.create_foreign_key('picture_repo_id_fkey', 'picture', 'repository', ['repo_id'], ['repo_id'])
    op.alter_column('picture', 'img_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('picture', 'pic_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('picture', 'repo_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
