"""Picture model changes

Revision ID: eadf4452f002
Revises: c0df4cd8ad9a
Create Date: 2022-05-29 21:38:17.231745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eadf4452f002'
down_revision = 'c0df4cd8ad9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picture', sa.Column('public_id', sa.String(), nullable=True))
    op.add_column('picture', sa.Column('secure_url', sa.String(), nullable=True))
    op.alter_column('picture', 'img_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('picture', 'img_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('picture', 'secure_url')
    op.drop_column('picture', 'public_id')
    # ### end Alembic commands ###
